### ISSUE TITLE
book should be stored in a git rep to track bugs & typos

### ISSUE THREAD

**Issue by clemsos** [costoffreedom/costoffreedom.cc#10]
What sort of export can we do with pubsweet allow ? only epub and html ? possible .tex or .md ?

**Comment by hellekin** [comment]
I'm working on porting the book to Markdown.

**Comment by clemsos** [comment]
wow ! tons of work ahead :) no way to export that from pubsweet ?

**Comment by hellekin** [comment]
bah, it's mostly copy-paste, and the most work is making the links between the pages anyway :)

I made some templates and already moved some texts... Will upload soonish so you can help :dancer:

**Comment by hellekin** [comment]
Here's an example: http://costoffreedom.cc/book/collective-memory/the-uncommon-creativity-of-bassel-khartabil
Not everything is there yet, but you can already browse to http://costoffreedom.cc/book

**Comment by clemsos** [comment]
awesome work ! how do you build the book ?
