### ISSUE TITLE
Update bio of Anasuya Sengupta

### ISSUE THREAD

**Issue by hellekin** [costoffreedom/costoffreedom.cc#11]
Need to update Anasuya's bio according to new data.

http://costoffreedom.cc/book/collective-memory/what-does-freedom-mean-to-you-mr-government

**Comment by clemsos** [comment]
new version : " Anasuya Sengupta is an advocate, strategist, and storyteller, currently on the Board of Directors of the Nonprofit Quarterly, an online and print publication that promotes an active and engaged democracy. She previously headed the Grantmaking department at the Wikimedia Foundation, and the Asia Pacific portfolio at the Global Fund for Women."
