### ISSUE TITLE
undesirable redirection from / to /book/index.html

### ISSUE THREAD

**Issue by mlinksva** [costoffreedom/costoffreedom.cc#27]
Because github pages don't support real redirection doing so on the homepage is a pretty bad user experience IMO. I suggest either some other material on the home page (could be very spare, link to book and non-book material, latter presumably communication mechanisms, news) or move the material at /book/ to the home page (fine to keep all the book material under /book/ of course).

**Comment by clemsos** [comment]
agree. this is awful
