### ISSUE TITLE
Add a link to download the press kit on the homepage

### ISSUE THREAD

**Issue by clemsos** [costoffreedom/costoffreedom.cc#34]
depends on #29 and #30

**Comment by mlinksva** [comment]
FWIW I don't understand benefit of separate presskit repo. If anything is useful enough to be in presskit it ought to be linkable from a URL like costoffreedom.cc/presskit/foo.jpg no? Don't folks these days typically download what they want from web rather than a zipfile of assets? Not that a zipfile couldn't be on the site too. Feel free to ignore, but I'm curious about the rationale as I see this pattern occasionally and each time scratch my head.

**Comment by clemsos** [comment]
sure, the URL should be /presskit/sth . I just thought it might be easier to maintain as a separate rep. It avoids to stuff everything into the website rep.

One thing that can easily be done from a separate rep is to generate a download link, so people interest can download the whole presskit at /presskit for instance.

Another way is to add the presskit rep as a submodule in the rep. Github will build it automatically as part of gh-pages/jekyll according to this doc https://help.github.com/articles/using-submodules-with-pages/ I have never tested it though.

**Comment by hellekin** [comment]
I suppose a press kit would contain high-definition of all images in the
book, plus a few interesting sources, contact for people, and a press
release.  Journalists like to copy-paste, don't they?

# 

hk

**Comment by clemsos** [comment]
yes, exactly. We can use pictures of the event from Chris and Barbara, also Bassel info can be imported from https://github.com/newpalmyra/press-kit

Need to write the press release - I will get that started this week. 

sort of depends on #39 - clean export to PDF for new versions of the book. Can you imagine there is no lib to properly create PDF from HTML in 2015 ? This never being solved sounds insane. No idea why...

**Comment by clemsos** [comment]
@mlinksva afterhought : you are right :) 
Let's have all together on the website. 
- I moved the book to https://github.com/costoffreedom/costoffreedom-book 
- I dropped the presskit rep 
- I added a presskit rep into gh-pages (check this branch https://github.com/costoffreedom/costoffreedom.cc/tree/gh-pages-no-book )

**Comment by mlinksva** [comment]
Why a separate repo for the book? How do changes to the book get published to the website in that case?

**Comment by mlinksva** [comment]
Oh nevermind, I see from the non-public list that the intent is for the book to live at book.costoffreedom.cc

**Comment by clemsos** [comment]
the separate repo for the book is because it makes things easier to generate clean PDF / epub + website from the source. Then we can have a small website to introduce the project at costoffreedom.cc

**Comment by mlinksva** [comment]
:+1: 

This does mean existing links to the book will 404. I'll create an issue about that.

**Comment by clemsos** [comment]
added a link to the presskit / about page in 3e2098d
