### ISSUE TITLE
Upload hi-res cover to Wikimedia Commons

### ISSUE THREAD

**Issue by clemsos** [costoffreedom/costoffreedom.cc#35]
uploading a high quality version of the cover image with adequate description of provenance to make it stick to Wikimedia Commons

https://github.com/costoffreedom/presskit/tree/master/cover

**Comment by mlinksva** [comment]
Close if https://commons.wikimedia.org/wiki/File:CostOfFreedom_Hi-RES_cover.jpg has accurate info, edit there or comment here if not. :)

**Comment by clemsos** [comment]
Great ! Thanks Mike :+1:
