### ISSUE TITLE
Add some pics from the booksprint to the presskit

### ISSUE THREAD

**Issue by clemsos** [costoffreedom/costoffreedom.cc#37]
pics here https://commons.wikimedia.org/wiki/Category:Cost_of_Freedom

**Comment by clemsos** [comment]
also @christopheradams pictures here https://www.facebook.com/adams.christopher.lee/media_set?set=a.500759570084009.1073741846.100004499103415&type=3

**Comment by hellekin** [comment]
On 02/22/2016 10:54 AM, Clément Renaud wrote:

> also @christopheradams https://github.com/christopheradams pictures
> here
> https://www.facebook.com/adams.christopher.lee/media_set?set=a.500759570084009.1073741846.100004499103415&type=3

How does the Image, Identity, Attribution, Authorship, work in this
case: I authorized Chris to shoot my portrait, but I also forbid
pictures of me on Facebook, Google, etc. for it grants _them_ the
copyright, and I don't want that to happen.

(BTW this link does not work: does it require login?)

# 

hk

## 

 _ _     We are free to share code and we code to share freedom
(_X_)yne Foundation, Free Culture Foundry \* https://www.dyne.org/donate/

**Comment by christopheradams** [comment]
On 02/22/2016 09:47 PM, hellekin wrote:

> On 02/22/2016 10:54 AM, Clément Renaud wrote:
> 
> > also @christopheradams https://github.com/christopheradams pictures
> > here
> > 
> > https://www.facebook.com/adams.christopher.lee/media_set?set=a.500759570084009.1073741846.100004499103415&type=3
> 
> How does the Image, Identity, Attribution, Authorship, work in this
> case: I authorized Chris to shoot my portrait, but I also forbid
> pictures of me on Facebook, Google, etc. for it grants _them_ the
> copyright, and I don't want that to happen.
> 
> (BTW this link does not work: does it require login?)

That link is not public, but your photo isn't in it anyway. I followed
your request. Copyright doesn't cover this issue, hence the inherent
risk taking of portraits.

Christopher

**Comment by hellekin** [comment]
Thanks Chris!  I knew I could trust you. (and a call to hackers: if this
guy comes to you to take your portrait, let him do :)

**Comment by christopheradams** [comment]
:)

**Comment by clemsos** [comment]
ok added the link to wikidata pics in the presskit
