### ISSUE TITLE
Handle book links to main site after book moves to subdomain

### ISSUE THREAD

**Issue by mlinksva** [costoffreedom/costoffreedom.cc#41]
Two obvious approaches:
- [404](https://help.github.com/articles/custom-404-pages/) page, might be able to have javascript redirect to pages on book subdomain 
- Brute force, stub for each book page on main site with js redirect to corresponding book subdomain page.

As mentioned in #34

**Comment by hellekin** [comment]
Don't use Javascript: let the server do it and keep track of URLs.

https://help.github.com/articles/redirects-on-github-pages/

It's not a nice nginx rewrite one-liner, but we can degrade gracefully
without having to resort to javascript in this case.

# 

hk

## 

 _ _     We are free to share code and we code to share freedom
(_X_)yne Foundation, Free Culture Foundry \* https://www.dyne.org/donate/

**Comment by mlinksva** [comment]
That uses javascript and only works within one jekyll site.

**Comment by clemsos** [comment]
Structure is similar on both meaning that for instance http://costoffreedom.cc/book/opening:freedom/ is now http://book.costoffreedom.cc/book/opening:freedom/

**Comment by mlinksva** [comment]
This should be done in 990484524cd5071f34d49f5fad67f9ed16361898 and fa9dd7456d2c294baf8be33861be7892509f56ee with a note added in 07b6ab73dda8a5716fce562c0d844849ada29722

I didn't notice til now 35d5e0b and #50 ... I like the 404 handler as a backup. I'd rather not completely remove the initial book URLs, especially the PDF.

**Comment by mlinksva** [comment]
That said I don't care that much. @clemsos feel free to just switch gh-pages to the 'clean' branch if that's what you think is best.

**Comment by clemsos** [comment]
I added the 404 as well, so we have both :) I think we can close this now.
