### ISSUE TITLE
add a section for HOWTO PARTICIPATE on the site

### ISSUE THREAD

**Issue by ghost** [costoffreedom/costoffreedom.cc#43]
There is currently no link to github organization here: http://costoffreedom.cc/

There is no information about how to join the mailing list or participate.

This is super important.

Where is the TODO list of tasks for moving this project forward?

**Comment by clemsos** [comment]
TODO list is here on github issues.

**Comment by clemsos** [comment]
Basically what is needed to finalize the work is 0.5 to 1 day work with 2-3 people on IRC to hammer all issues here one by one

**Comment by ghost** [comment]
I added github link. Is anyone on the mailing list? How about nuke it, push all to github.

**Comment by mlinksva** [comment]
I'm fine with not using the mailing lists.

A `CONTRIBUTING.md` file is a good place to put howto participate stuff if it should be visible in the repository. If exists is linked to when eg opening an issue.

**Comment by ghost** [comment]
Sure go for it.

I am more concerned with how to get more people tk read the book and then a
clear path to the site which should then have a clear and simple path to
contribute. Make sense?

**Comment by mlinksva** [comment]
Sure.

I think the biggest barrier to contributing will be lack of clear direction about how we want people to participate.

Thinking out loud, do we want them to:
- suggest copyedits (yes)
- read the book (yes)
- share the book (yes)
- review the book (yes)
- buy hardcopies (yes)
- add chapters (?; if so we should make editorial process somewhat clear)
- make translations (yes; but suggestions of how to proceed would help)
- do other #freebassel actions (yes)
- what else?

Whatever the stuff we really want people to do should be obvious from the book, the site, and the repo, any of which people might visit first. I'll think about how to do that, but other thoughts welcome.

The even bigger barrier though is people learning abut the book at all, which requires promotion outside of those venues...

**Comment by ghost** [comment]
Exactly

On Sunday, February 21, 2016, Mike Linksvayer notifications@github.com
wrote:

> Sure.
> 
> I think the biggest barrier to contributing will be lack of clear
> direction about how we want people to participate.
> 
> Thinking out loud, do we want them to:
> - suggest copyedits (yes)
> - read the book (yes)
> - share the book (yes)
> - review the book (yes)
> - buy hardcopies (yes)
> 
> All seem doable
> - add chapters (?; if so we should make editorial process somewhat
>   clear)
> 
> I think this is hard, but possible. Better to clean up what exists
> - make translations (yes; but suggestions of how to proceed would help)
> - do other #freebassel actions (yes)
> 
> Will happn regardless. Main thing would be to link to the days.
> - what else?
> 
> Whatever the stuff we really want people to do should be obvious from the
> book, the site, and the repo, any of which people might visit first. I'll
> think about how to do that, but other thoughts welcome.
> 
> The even bigger barrier though is people learning abut the book at all,
> which requires promotion outside of those venues...

Yes. If we going to release, we should treat this as never having been
released which means soooo many people dont know about this book. It helps
give direction too right?

Jon

**Comment by mlinksva** [comment]
> Yes. If we going to release, we should treat this as never having been released which means soooo many people dont know about this book. It helps give direction too right?

Yes. Substantial promotion as new release makes the rest worthwhile. Made a new issue #49

**Comment by hellekin** [comment]
> - add chapters (?; if so we should make editorial process somewhat clear)

I'd rather have "CoF 2" than add chapters to this one.  It was a five
days process, remember?

**Comment by ghost** [comment]
Agree

**Comment by mlinksva** [comment]
Adding chapters would be a post new/re-release thing in any case.

But I'm not sure IF the project continues actively after that release it would be best to conceptualize as something that has editions rather than just ongoing updates, like a wiki, but in primarily viewed in book form. Otherwise it is just one of [many](http://www.adamhyde.net/books-are-evil-really-evil/) "artefacts that maintain proprietary knowledge culture", but then this project is already a heresy-on-a-heresy, turning a booksprint-produced book into [markdown](http://www.adamhyde.net/whats-wrong-with-markdown/) managed with git. :trollface:

**Comment by hellekin** [comment]
On 02/22/2016 05:29 PM, Mike Linksvayer wrote:

> http://www.adamhyde.net/whats-wrong-with-markdown/

Unless you need LaTeX for formulas, I think Markdown is the closest to
plain text you can get, and quite comfortable for writing books--made of
text.  I tend to prefer Orgmode for the power behind the scenes, but
Markdown gives what it advertises: simple text that is converted into
HTML with proper typography, spacing, etc.  Most of the time, authors
will use plain text anyway (not many books make extensive use of
typography besides Bold, Italic, and Blockquote, which are covered by
Markdown).

This seems to me like arguing over the quality of the cover regardless
of the contents of the book.

# 

hk

## 

 _ _     We are free to share code and we code to share freedom
(_X_)yne Foundation, Free Culture Foundry \* https://www.dyne.org/donate/

**Comment by christopheradams** [comment]
On 02/23/2016 02:14 AM, hellekin wrote:

> text. I tend to prefer Orgmode for the power behind the scenes, but

Offtopic, but Orgmode is great. Github even supports the format. Try
README.org in your next project.

**Comment by clemsos** [comment]
hey guys, I added some basic instructions in this commit  0665bb0b98a2a2222377e0c1ca7dadc4dbc876e5

**Comment by ghost** [comment]
Great job.
