### ISSUE TITLE
Get reviews of the book and link on the site

### ISSUE THREAD

**Issue by ghost** [costoffreedom/costoffreedom.cc#45]
simple, right?

**Comment by clemsos** [comment]
Actually this should be solved by #40 i.e adding news on the homepage. This is done already on the gh-pages-no-book branch but need some styling

**Comment by clemsos** [comment]
added in c765b0f1f104dd6b3eb6e8582d7f80de055e4410 and c4c90f57276f16a6740b49ecd1750f6792182cf9
