### ISSUE TITLE
release book on lulu

### ISSUE THREAD

**Issue by ghost** [costoffreedom/costoffreedom.cc#48]
so can get into shops

**Comment by clemsos** [comment]
depends on costoffreedom/costoffreedom-book#5 -- see #49

**Comment by clemsos** [comment]
ok done for the epub version. still need a print version http://www.lulu.com/shop/collective-book-sprint/cost-of-freedom/ebook/product-22600256.html

**Comment by mlinksva** [comment]
I get "Hmmm, we can't find this product, but we have many other great offerings! Continue Shopping"

Random note, two other books on Lulu called "The Cost of Freedom"
- http://www.lulu.com/shop/german-israel-villanueva/the-cost-of-freedom/ebook/product-17357718.html
- http://www.lulu.com/shop/steve-streeter/the-cost-of-freedom/paperback/product-18665781.html

**Comment by clemsos** [comment]
ok should work now.

**Comment by mlinksva** [comment]
How's hardcopy at Lulu coming?

**Comment by mlinksva** [comment]
Ping.

Also, does Lulu take care of making available on Amazon? Many consider being on Amazon necessary (but definitely not sufficient) for being a real book.

**Comment by ghost** [comment]
Yeah, that's a Christopher question. For the Waiting book, that was the
path to get onto Amazon, and it takes time, so need to post at least 2
weeks before to get in. Also, I know the lulu CEO so can goose along.

We should also get this up on the cc book store. Filing another issue about
that.

**Comment by clemsos** [comment]
![selection_116](https://cloud.githubusercontent.com/assets/743246/14912067/1de64724-0dfa-11e6-829e-6167a9ea442a.png)

almost there

**Comment by clemsos** [comment]
OK the thing is up on Lulu : http://www.lulu.com/shop/book-sprint/cost-of-freedom/paperback/product-22674262.html
