### ISSUE TITLE
Download link on homepage should point to the latest book build

### ISSUE THREAD

**Issue by clemsos** [costoffreedom/costoffreedom.cc#51]

**Comment by ghost** [comment]
Interesting idea. Maybe should be more like software, the book download
button is the most stable, and then there is a smaller link to the latest
dev build.

Jon

**Comment by mlinksva** [comment]
https://github.com/costoffreedom/costoffreedom.cc/commit/72833a7523a237554505b1d076bbd4e72eba95ee
