### ISSUE TITLE
added twitter conversation widget

### ISSUE THREAD

**Issue by ghost** [costoffreedom/costoffreedom.cc#52]
yeah!

and center it

**Comment by ghost** [comment]
Done

**Comment by mlinksva** [comment]
#costoffreedom seems to be dominated by tweets about a TV show of that name https://en.wikipedia.org/wiki/The_Cost_of_Freedom

I think we should  use that hashtag when tweeting about the book so as to pollute their drivel, but I don't think we should be displaying their drivel on the home page. I'd say revert.

**Comment by clemsos** [comment]
yes, agree. the hashtag channel is polluted - also used by US war proponents . See this thread for some fun :) https://twitter.com/hellekin/status/664490709676859393

**Comment by ghost** [comment]
Or talk more or change the hashtag
