### ISSUE TITLE
links and bassel-tweets pages

### ISSUE THREAD

**Issue by mlinksva** [costoffreedom/costoffreedom.cc#54]
Aren't up to date on site design. I tried to fix the links one, sort of. It still looks bad.

Is the list of links an output of the sprint? That kind of page seems like from the web of the 1990s. There's probably a Wikipedia page or two that would serve readers better.

On the tweets, super important file, but shouldn't it be on freebassel.org ?

**Comment by ghost** [comment]
What page of links? urL?

The current main page with updates looks good and is spot on. Yes, the
bassel tweets is already live here: http://kiki.wiki/bassel/

And if needs to be more detailed should go to freebassel.org agree.

**Comment by mlinksva** [comment]
http://costoffreedom.cc/links.html
http://costoffreedom.cc/bassel-tweets/

**Comment by ghost** [comment]
Oh, the links are fine, as are part of the book appendix.

The bassel tweets, no idea, replicate everywhere. @clement @clemsos was
there a plan for those?

Jon

**Comment by clemsos** [comment]
No plan. Let's remove bassel's tweets from here. The links can be removed as well, I don't think they serve a purpose. Maybe we can keep them as README file or sth

**Comment by mlinksva** [comment]
Glad to see the progress @clemsos 

Do the tweets exist somewhere else? Would love to put in a redirect. http://kiki.wiki/bassel/ looks great but can't download, search, etc. Hmm, maybe solution is to upload to archive.org. I'll do that and figure out where to put a link. Re-opening and assigning to me.

**Comment by mlinksva** [comment]
I put the tweets up at https://archive.org/details/bassel_khartabil_tweets_archive for anyone wishing to start a project around them.
