### ISSUE TITLE
Get book up on cc bookstore

### ISSUE THREAD

**Issue by ghost** [costoffreedom/costoffreedom.cc#56]
Like the waiting book

**Comment by clemsos** [comment]
What's the process for that ?

**Comment by ghost** [comment]
Jon does when its ready

**Comment by clemsos** [comment]
hey, looks like it is ready now. see the final PDF here https://github.com/costoffreedom/costoffreedom-book/blob/master/costoffreedom-final.pdf

**Comment by ghost** [comment]
Asked to get it up here: http://creativecommons.org/discover/gift-guide/

**Comment by ghost** [comment]
Ok, another path taken, so look out for some noise ;)
