### ISSUE TITLE
Book on Amazon

### ISSUE THREAD

**Issue by mlinksva** [costoffreedom/costoffreedom.cc#64]
Tracking; maybe 2 weeks after publication on Lulu -- https://github.com/costoffreedom/costoffreedom.cc/issues/48#issuecomment-202697440 ?

Curiosity: Bassel t-shirts from vendors that seem to put random stuff from the internet on t-shirts: [1](http://www.amazon.com/Missing-Bassel-T-Shirt-Heather-Gray/dp/B01BPGK6OM?ie=UTF8&keywords=khartabil&qid=1464494919&sr=8-6) [2](http://www.amazon.com/POCOO-Freebassel-Cotton-T-shirt-black/dp/B01E59HY28?ie=UTF8&keywords=freebassel&qid=1464494757&sr=8-1)

**Comment by clemsos** [comment]
yes, still have to wait 6-8 weeks. I had to wait for the trial print to be shipped so I can validate the distribution channels (which I did today). so 6+ weeks from now :(

**Comment by ghost** [comment]
Progress though :) is this normal timeline for this?

Jon

**Comment by clemsos** [comment]
@rejon yes, it looks like it

**Comment by clemsos** [comment]
Ha, I just figured out that the book is actually on sale on Amazon :) 
https://www.amazon.fr/Cost-Freedom-Book-Sprint/dp/1365086984/ref=sr_1_22?ie=UTF8&qid=1478241878&sr=8-22&keywords=cost+of+freedom
