### ISSUE TITLE
Page build fails but requires URL changes to pass

### ISSUE THREAD

**Issue by clemsos** [costoffreedom/costoffreedom.cc#66]
I just added new palmyra as a sponsor of the book but the site won't rebuild (see this commit b0ad5dc0edb8aa57d6fa11770bd7bd32684c73d0 ).

Github has upgraded to Jekyll 3 since we made this website which does not support colon in URLs. When I try to build on my local install with the gh-pages I got this error

```
 Incremental build: disabled. Enable with --incremental
      Generating... 
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    The URL /book/opening:freedom/costs-of-openness/ is invalid because it contains a colon.
```

Changing the folder name will lead to dead linking, so I am not sure how to update this.  
Ideas anyone ?
(and happy new year =)

**Comment by christopheradams** [comment]
There is a jekyll redirect plugin supported by Github pages.

I also recommend developing with the github-pages gem (using Bundler) rather than plain Jekyll so you get consistent builds locally and on GitHub.

**Comment by mlinksva** [comment]
I've not tested but possible workaround in https://github.com/jekyll/jekyll/issues/5284#issuecomment-250285194

**Comment by clemsos** [comment]
Thanks @mlinksva ! it works

@christopheradams yep, and also need to update my ghpages gem has I didn't update for last 6 months and versions have changed now

**Comment by mlinksva** [comment]
The included https://rubygems.org/gems/jekyll-redirect-from only works if destination is on same site (from not to).

https://github.com/costoffreedom/costoffreedom.cc/commit/09c0447cc24abd15f32e6c04ffd0fea8e33778bb#diff-8b7db4d5cc4b8f6dc8feb7030baa2478 should make you update your pages gem if it is out of date.
