### ISSUE TITLE
book.costoffreedom.cc obtains DNS error

### ISSUE THREAD

**Issue by mlinksva** [costoffreedom/costoffreedom.cc#69]
Linked to for HTML version on home page

**Comment by clemsos** [comment]
We were using Gitbook and they made many upgrades, so that may have break the existing version. Let me see how to arrange that

**Comment by clemsos** [comment]
I updated to new DNS on gitbook, populating now...

**Comment by clemsos** [comment]
fixed https://book.costoffreedom.cc
